// src/components/FutureDays.svelte
<script>
  import dayjs from 'dayjs';

  const theFuture = (daysToShow) =>
    Array(daysToShow)
      .fill(Math.ceil(daysToShow / 2) * -1)
      .map((day, idx) =>
        dayjs()
          .add(idx + day, 'day')
          .format('DD. MMM')
      );
</script>

<div class="FutureDays">
  {#each theFuture(7) as day}
    <div>{day}</div>
  {/each}
</div>

<style>
  .FutureDays {
    display: flex;
    width: 100%;
    justify-content: space-between;
  }
</style>

// src/views/FutureDays.jsx
import m from 'mithril';
import dayjs from 'dayjs';

const theFuture = Array(7)
  .fill(-3)
  .map((day, idx) =>
    dayjs()
      .add(idx + day, 'day')
      .format('DD. MMM')
  );

export const FutureDays = {
  view: () => (
    <div className="FutureDays">
      {theFuture.map((day) => (
        <div className="Day">{day}</div>
      ))}
    </div>
  ),
};
