// src/views/Habits.svelte
<script lang="ts">
  import { Habit } from '../models/Habit';
  import { HabitPoint } from '../models/HabitPoint';
  import FutureDays from './FutureDays.svelte';
</script>

{#if Habit.list.length > 0}
  <div class="Habits">
    <FutureDays />
    {#each Habit.list as { title, _id }}
      <div class="Habit">
        <button class="Track" on:click={() => HabitPoint.add(_id)}> 🏋️‍♂️ </button>
        <span>{title}</span>
      </div>
    {/each}
  </div>
{:else}
  <div class="Empty">
    🥵 your habit list is awfully empty, time to get cracking
  </div>
{/if}

<style>
  .Habits {
    display: grid;
  }

  .Habit {
    border-right: 2px solid #3c5bff;
    border-bottom: 2px solid #3c5bff;
    padding: 22px 36px;
  }

  .Habit:last-child {
    border-bottom: 0;
  }

  .Track {
    background-color: transparent;
    appearance: none;
    border: none;
    text-decoration: underline;
  }

  .Empty {
    text-align: center;
  }
</style>

// src/views/Habits.tsx
import m from 'mithril';
import { Habit } from '../models/Habit';
import { HabitPoint } from '../models/HabitPoint';
import { FutureDays } from './FutureDays';

export const Habits = () =>
  Habit.list.length > 0 ? (
    <div className="Habits">
      <FutureDays />
      {Habit.list.map(({ title, _id }) => (
        <div className="Habit">
          <button className="Track" onclick={() => HabitPoint.add(_id)}>
            🏋️‍♂️
          </button>
          <span>{title}</span>
        </div>
      ))}
    </div>
  ) : (
    <div style={{ textAlign: 'center' }}>
      🥵 your habit list is awfully empty, time to get cracking
    </div>
  );
